services:
  - type: web
    name: visiblaze-backend
    runtime: docker
    rootDir: backend
    envVars:
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false

  - type: web
    name: visiblaze-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: visiblaze-backend
          type: web
          property: host
